name: Deploy to AWS EC2

on:
  push:
    branches:
      - feature/api

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: churn-prediction
  IMAGE_TAG: seif_khalil-662
  GITHUB_REPO: https://github.com/OPCoderman/MLOps-Course-Labs.git

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run unit tests
      run: pytest

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to ECR
      env:
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
        AWS_REGION: ${{ env.AWS_REGION }}
      run: |
        IMAGE_URI=$(aws ecr describe-repositories --repository-names $ECR_REPOSITORY --region $AWS_REGION --query 'repositories[0].repositoryUri' --output text)
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $IMAGE_URI:$IMAGE_TAG
        docker push $IMAGE_URI:$IMAGE_TAG

    - name: SSH and deploy on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Clone or pull the repo
          if [ ! -d MLOps-Course-Labs ]; then
            git clone $GITHUB_REPO
          else
            cd MLOps-Course-Labs && git pull
          fi

          cd MLOps-Course-Labs
          # Update docker-compose.yml to use the pushed image
          sed -i 's|image: .*|image: '"$IMAGE_URI:$IMAGE_TAG"'|' docker-compose.yml

          # Run docker-compose
          docker-compose up -d --build
